Add missing dependency on the math library
while building gnucash,

...
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: libgnucash/app-utils/CMakeFiles/gncmod-app-utils.dir/calculation/fin.c.o: in function `eff_int':
/home/abuild/rpmbuild/BUILD/gnucash-3.7/build/../libgnucash/app-utils/calculation/fin.c:1505: undefined reference to `pow'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/gnucash-3.7/build/../libgnucash/app-utils/calculation/fin.c:1509: undefined reference to `exp'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: libgnucash/app-utils/CMakeFiles/gncmod-app-utils.dir/calculation/fin.c.o: in function `_fi_calc_num_payments':
/home/abuild/rpmbuild/BUILD/gnucash-3.7/build/../libgnucash/app-utils/calculation/fin.c:1289: undefined reference to `log'
...