Fix invalid-$DISPLAY error being non-text
Given
  nabijaczleweli@tarta:~$ DISPLAY=komputerek-x40.:0 gnucash
  Run 'g --help' to see a full list of available command line options.
  Error: could not initialise graphical user interface and option add-price-quotes was not set.
  Perhaps you need to set the $DISPLAY environment variable?nabijaczleweli@tarta:~$
we can obviously see the error output isn't a text file.