gnc-autoclear: ATTEMPT use shared_ptr
seems straightforward but...

it wants to sizeof split_s or something

[3/60] Building CXX object gnucash/gnome-utils/CMakeFiles/gnc-gnome-utils.dir/gnc-autoclear.cpp.o
FAILED: gnucash/gnome-utils/CMakeFiles/gnc-gnome-utils.dir/gnc-autoclear.cpp.o
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_REGEX_DYN_LINK -DGNC_VCS=\"git\" -DG_LOG_DOMAIN=\"gnc.gui\" -DHAVE_CONFIG_H -DHAVE_GUILE30 -D_GNU_SOURCE -Dgnc_gnome_utils_EXPORTS -I/home/chris/sources/gnucash/maint/gnucash/gnome-utils -Ignucash/gnome-utils -I/home/chris/sources/gnucash/maint/libgnucash/app-utils -I/home/chris/sources/gnucash/maint/libgnucash/engine -Icommon -I/home/chris/sources/gnucash/maint/common -I/home/chris/sources/gnucash/maint/borrowed/libc -Ilibgnucash/core-utils -I/home/chris/sources/gnucash/maint/libgnucash/core-utils -I/home/chris/sources/gnucash/maint/libgnucash/tax -I/home/chris/sources/gnucash/maint/bindings/guile -I/usr/include/guile/3.0 -I/usr/include/libxml2 -I/home/chris/sources/gnucash/maint/libgnucash/backend/xml -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/gtk-3.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/harfbuzz -isystem /usr/include/fribidi -isystem /usr/include/atk-1.0 -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -Wno-error=deprecated-declarations  -Werror -Wall -Wmissing-declarations -Wno-unused -Wno-error=parentheses  -g -fPIC -Wno-deprecated-declarations -pthread -std=c++17 -MD -MT gnucash/gnome-utils/CMakeFiles/gnc-gnome-utils.dir/gnc-autoclear.cpp.o -MF gnucash/gnome-utils/CMakeFiles/gnc-gnome-utils.dir/gnc-autoclear.cpp.o.d -o gnucash/gnome-utils/CMakeFiles/gnc-gnome-utils.dir/gnc-autoclear.cpp.o -c /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp
In file included from /usr/include/c++/11/bits/shared_ptr_base.h:60,
                 from /usr/include/c++/11/bits/shared_ptr.h:53,
                 from /usr/include/c++/11/memory:77,
                 from /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:28:
/usr/include/c++/11/ext/aligned_buffer.h: In instantiation of ‘struct __gnu_cxx::__aligned_buffer<split_s>’:
/usr/include/c++/11/bits/shared_ptr_base.h:506:35:   required from ‘class std::_Sp_counted_ptr_inplace<split_s, std::allocator<split_s>, __gnu_cxx::_S_atomic>::_Impl’
/usr/include/c++/11/bits/shared_ptr_base.h:567:13:   required from ‘class std::_Sp_counted_ptr_inplace<split_s, std::allocator<split_s>, __gnu_cxx::_S_atomic>’
/usr/include/c++/11/bits/shared_ptr_base.h:647:43:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = split_s; _Alloc = std::allocator<split_s>; _Args = {split_s*&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:1342:14:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<split_s>; _Args = {split_s*&}; _Tp = split_s; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr.h:409:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<split_s>; _Args = {split_s*&}; _Tp = split_s]’
/usr/include/c++/11/bits/shared_ptr.h:862:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = split_s; _Alloc = std::allocator<split_s>; _Args = {split_s*&}]’
/usr/include/c++/11/bits/shared_ptr.h:878:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = split_s; _Args = {split_s*&}]’
/home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:145:45:   required from here
/usr/include/c++/11/ext/aligned_buffer.h:91:28: error: invalid application of ‘sizeof’ to incomplete type ‘split_s’
   91 |     : std::aligned_storage<sizeof(_Tp), __alignof__(_Tp)>
      |                            ^~~~~~~~~~~
/usr/include/c++/11/ext/aligned_buffer.h:91:28: error: invalid application of ‘sizeof’ to incomplete type ‘split_s’
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:26:
/usr/include/c++/11/type_traits: In instantiation of ‘struct std::is_nothrow_constructible<split_s, std::shared_ptr<split_s>&>’:
/usr/include/c++/11/bits/alloc_traits.h:509:57:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = split_s; _Args = {std::shared_ptr<split_s>&}; _Tp = split_s; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<split_s>]’
/usr/include/c++/11/bits/shared_ptr_base.h:519:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::shared_ptr<split_s>&}; _Tp = split_s; _Alloc = std::allocator<split_s>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:650:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = split_s; _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:1342:14:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}; _Tp = split_s; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr.h:409:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}; _Tp = split_s]’
/usr/include/c++/11/bits/shared_ptr.h:862:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = split_s; _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}]’
/usr/include/c++/11/bits/shared_ptr.h:878:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = split_s; _Args = {std::shared_ptr<split_s>&}]’
/home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:168:52:   required from here
/usr/include/c++/11/type_traits:1017:25: error: invalid use of incomplete type ‘struct split_s’
 1017 |       = __bool_constant<__is_nothrow_constructible(_Tp, _Args...)>;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/chris/sources/gnucash/maint/libgnucash/engine/Account.h:48,
                 from /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:33:
/home/chris/sources/gnucash/maint/libgnucash/engine/gnc-engine.h:152:16: note: forward declaration of ‘struct split_s’
  152 | typedef struct split_s               Split;
      |                ^~~~~~~
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:26:
/usr/include/c++/11/type_traits:1025:52: error: static assertion failed: template argument must be a complete class or an unbounded array
 1025 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/type_traits:1025:52: note: ‘std::__is_complete_or_unbounded<std::__type_identity<split_s> >((std::__type_identity<split_s>{}, std::__type_identity<split_s>()))’ evaluates to false
In file included from /usr/include/c++/11/ext/alloc_traits.h:34,
                 from /usr/include/c++/11/bits/stl_uninitialized.h:64,
                 from /usr/include/c++/11/memory:66,
                 from /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:28:
/usr/include/c++/11/bits/alloc_traits.h: In instantiation of ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = split_s; _Args = {std::shared_ptr<split_s>&}; _Tp = split_s; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<split_s>]’:
/usr/include/c++/11/bits/shared_ptr_base.h:519:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::shared_ptr<split_s>&}; _Tp = split_s; _Alloc = std::allocator<split_s>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:650:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = split_s; _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:1342:14:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}; _Tp = split_s; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr.h:409:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}; _Tp = split_s]’
/usr/include/c++/11/bits/shared_ptr.h:862:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = split_s; _Alloc = std::allocator<split_s>; _Args = {std::shared_ptr<split_s>&}]’
/usr/include/c++/11/bits/shared_ptr.h:878:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = split_s; _Args = {std::shared_ptr<split_s>&}]’
/home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:168:52:   required from here
/usr/include/c++/11/bits/alloc_traits.h:509:64: error: ‘value’ is not a member of ‘std::is_nothrow_constructible<split_s, std::shared_ptr<split_s>&>’
  509 |         noexcept(std::is_nothrow_constructible<_Up, _Args...>::value)
      |                                                                ^~~~~
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/chris/sources/gnucash/maint/gnucash/gnome-utils/gnc-autoclear.cpp:26:
/usr/include/c++/11/type_traits: In instantiation of ‘struct std::is_nothrow_destructible<split_s>’:
/usr/include/c++/11/bits/alloc_traits.h:528:41:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::destroy(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*) [with _Up = split_s; _Tp = split_s; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<split_s>]’
/usr/include/c++/11/bits/shared_ptr_base.h:528:35:   required from ‘void std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_dispose() [with _Tp = split_s; _Alloc = std::allocator<split_s>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/11/bits/shared_ptr_base.h:526:7:   required from here
/usr/include/c++/11/type_traits:939:52: error: static assertion failed: template argument must be a complete class or an unbounded array
  939 |       static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/type_traits:939:52: note: ‘std::__is_complete_or_unbounded<std::__type_identity<split_s> >((std::__type_identity<split_s>{}, std::__type_identity<split_s>()))’ evaluates to false
ninja: build stopped: subcommand failed.